---
name: Check pull requests
on:
  pull_request:
    branches-ignore:
      - '1.x'

concurrency:
  group: "check-pull-request-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [
          { 'version': '17', 'opts': '' },
          { 'version': '21', 'opts': '' },
          { 'version': '25', 'opts': '' }
        ]
    name: Build with Java ${{ matrix.java.version }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        name: set up jdk ${{matrix.java.version}}
        with:
          distribution: temurin
          java-version: ${{matrix.java.version}}
          cache: maven
      - name: Build with Maven
        env:
          MAVEN_OPTS: ${{ matrix.java.opts }}
        run: ./mvnw --no-transfer-progress -s .build/maven-ci-settings.xml -B clean verify -Pcoverage
      - name: Codecov
        uses: codecov/codecov-action@v5.5.1

  conventional-commits:
    runs-on: ubuntu-latest
    name: Check conventional commits
    steps:
      - uses: actions/checkout@v5
      - uses: wagoid/commitlint-github-action@v6
        if: (github.actor!= 'dependabot[bot]') && (contains(github.head_ref, 'dependabot/') == false)

  compatibility:
    runs-on: ubuntu-latest
    name: Compatibility Check
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Compatibility Check
        run: ./mvnw --no-transfer-progress -s .build/maven-ci-settings.xml -pl '!bom' -B install revapi:check@check-compatibility -DskipTests -fae

  documentation:
    runs-on: ubuntu-latest
    name: Documentation build check
    steps:
      - uses: actions/checkout@v5
        name: Checkout code
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - uses: actions/setup-python@v6
        name: Set up Python
        with:
          python-version-file: "documentation/pyproject.toml"
      - name: Other tools setup
        run: sudo snap install yq
      - name: Render docs
        run: |
          cd documentation
          uv sync --all-extras --dev
          uv run mkdocs build
