---
name: Main branch continuous integration
on:
  push:
    branches:
      - "main"

concurrency:
  group: "ci-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Test the main branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Run the tests
        run: ./mvnw --no-transfer-progress -s .build/maven-ci-settings.xml -B clean verify
